
<tr>
	<td class="center">
			<label>
			<input type="checkbox" class="ace" />
		<span class="lbl"></span>
			</label>
	</td>
    
    <td width="36%"><a href="/admin/registration/detail/id/<?php echo $this->id; ?>"><?php echo ($this->name)?$this->name: $this->first_name. '' .$this->last_name; ?></a></td>
	<td><?php echo $this->mobile; ?></td>
	<td> <?php echo $this->email; ?> </td>
	<td> <?php echo date('d/m/Y',$this->created_at); ?> </td>
    <td><?php echo $this->calitext; ?></td>
    <td><?php echo ($this->vip)?'Có':'Không'; ?></td>
    <td><?php echo ($this->used_service)?'Có':'Không'; ?></td>
    <td width="6%" class="text-center">
	    <a class="orange" data-id="<?php echo $this->id; ?>" href="javascript:void(0);" onclick="toggleStatus(this, <?php echo (($this->status)?0:1); ?>)"><i class="fa fa-eye<?php echo (($this->status)?'':'-slash'); ?> bigger-130"></i></a>
    </td>
    <td class="text-center" width="6%">
	    <a onclick="return confirm('Bạn muốn xóa?');" class="red" href="/admin/registration/delete/id/<?php echo $this->id; ?>"><i class="fa fa-trash bigger-130"></i></a>
    </td>
</tr>

