<div id="footer">
<div class="panel-box footer">
	    <div class="row no-gutter">
	   	 	<div class="border-page-footer col-md-10 col-md-offset-1">
		  
		   	 	 <div class="row col-md-12 col-md-offset-0">
			   	 	 <div class="office-box col-md-4 npl col-first">
			   	<span class="n2"> <img class="img-defer" data-src="<?=TEMPLATE_URL?>/default/img/icon-01.png"/></span>
			   <div class="f11a1">
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>29 Doan Thi Diem str, Dong Da dist.</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>
	<a class="click2call" href="tel:02437325976">024.3732.5976</a> - <a class="click2call" href="tel:02437325978">024.3732.5978</a></div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i><a class="click2call" href="tel:0913311911">+84.913.311.911</a> - info@hoabinhtourist.com</div>


			   </div>
		   	 	</div>
			   	 	 <div class="office-box col-md-4">
		  	<span class="n2"> <img class="img-defer" data-src="<?=TEMPLATE_URL?>/default/img/icon-02.png"/></span>
			   <div class="f11a1">
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>217 Tran Phu str, Hai Chau dist.</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i><a class="click2call" href="tel:02363996116">0236.399.6116</a> - <a class="click2call" href="tel:02363996226">0236.399.6226</a> </div>
<div class="at1">
<i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i><a class="click2call" href="tel:0913186829">+84.913.186.829</a> - info@danangevents.com.vn</div>


			   </div>
			   	 <!--	<a href="#" />
			   	 		<img src="http://vietnamevents.com/images/memberof.png" />
			   	 	</a>-->
		   	 	</div>
		   	 	
			   	 	 <div class="office-box col-md-4">
		<span class="n2"> <img class="img-defer" data-src="<?=TEMPLATE_URL?>/default/img/icon-03.png"/></span>
<div class="f11a1">			
	<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>05 Hoa Cau str., Phu Nhuan dist</div>   	 	
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i><a class="click2call" href="tel:02835178383">028.3517.8383</a> - <a class="click2call" href="tel:02835171797">028.3517.1797</a> </div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i><a class="click2call" href="tel:0905388666">+84.905.388.666</a></div>

		   	 	</div>
		   	 	</div>
		   	 	 </div>
		   	 	<div class="row col-md-12 col-md-offset-0">
			   
		   	 	</div>
		   	 	 <div class="col-menu-footer col-md-12 col-md-offset-0">
			   	 	
		   	 	<div class="col-md-12 menu-footer">
			   	 	 <div class="row">

		   	 	<ul class="list-inline pull-left">
			   
    				<li><a title="<?php echo $this->translate('home'); ?>" href="/"><?php echo $this->translate('home'); ?></a></li>
					<li><a title="<?php echo $this->translate('about'); ?>" href="<?php echo $this->translate('footer_link_1'); ?>"><?php echo $this->translate('about'); ?></a></li>
					<li><a title="<?php echo $this->translate('activity'); ?>" href="<?php echo $this->translate('footer_link_2'); ?>"><?php echo $this->translate('activity'); ?></a></li>
					<li><a title="<?php echo $this->translate('news'); ?>" href="<?php echo $this->translate('news_link'); ?>"><?php echo $this->translate('news'); ?></a></li>
					<li><a title="<?php echo $this->translate('rec'); ?>" href="<?php echo $this->translate('footer_link_3'); ?>"><?php echo $this->translate('rec'); ?></a></li>
					<li><a title="<?php echo $this->translate('contact'); ?>" href="<?php echo $this->translate('footer_link_4'); ?>"><?php echo $this->translate('contact'); ?></a></li>
					<li><a title="<?php echo $this->translate('membership'); ?>" href="http://membershipcard.hoabinh-group.com/"><?php echo $this->translate('membership'); ?></a></li>
					<li><a title="<?php echo $this->translate('gallery'); ?>" href="/gallery"><?php echo $this->translate('gallery'); ?></a></li>					
					
				</ul>
		   	 		</div>
		   	 	</div>	
		   	 		
		   	 	<div class="col-md-12 newsletter">
			   	 	<div class="row">
			   	 	<div class="col-md-2 col-sm-12 register">
				   	 	<div class="row">
				   	 	<img class="img-defer" data-src="/public/templates/news2017/default/img/email.png">
				   	 	<span><?php echo $this->translate('newsletter_1','<br/>'); ?></span>
				   	 
				   	 	</div></div>
				   	 	<div class="">
			   	 	<div class="col-md-7 col-xs-12">
				   	 	
				   	 	<div class="register-info col-md-5 npl npr">
				   	 	<span>
				   	 <?php echo $this->translate('newsletter_2','<br/>'); ?>	
				   	 					 </span>
				   	 	</div>
				   	 	<div style="margin-top: 5px;" class="form-newsletter col-md-6 col-xs-12">
					<form action="http://send.hoabinhtourist.com/lists/5d658412ad20f/embedded-form-subscribe-captcha" method="POST" class="">   	 	
					   	 	<div class="form-group">
				<input type="text" class="form-control" id="EMAIL" name="EMAIL" required pattern="[^@]+@[^@]+\.[a-zA-Z]{2,6}" placeholder="<?php echo $this->translate('input_email'); ?>">
				<input type="submit" class="btn" value="<?php echo $this->translate('register'); ?>">

					   	 	</div>
					</form>   	 	
				   	 	</div>
				   	 	
				   	 	</div>
				   	 
			   	 	<div class="col-md-3 col-xs-12 social">
				   	 	<div class="row">
					 <ul class="social-list list-inline">
				   	 <li>	<a target="_blank" rel="nofollow" href="https://www.facebook.com/events.hoabinhgroup/"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>  </li>
				   	 <li>	<a target="_blank" rel="nofollow" href="https://plus.google.com/100126685922991503903"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
				   	 	<li><a target="_blank" rel="nofollow" href="https://www.youtube.com/channel/UC-7G_1GDT_sNka83OrvXUzQ"><i class="fa fa-youtube-square" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="+84989898198"><i class="fa fa-whatsapp" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="Jackiehan29"><i class="fa fa-weixin" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="touroperator68"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
					   	 	</ul>
				   	 	
			   	 	
				   	 	</div>
				   	 </div>
				   	 	</div>
			   	 	</div>
		   	 	</div>
		   	 	
		   	 	
		   	
	   	 	</div>
	    </div>
      </div>
    
</div>
</div>
<?php
	//$identity = Zend_Auth::getInstance()->getIdentity();
	// if (isset($identity) && ($identity->id == 3)) { ?>
	<!--<div class="social-mxh"><div class="social-mxh-text">CONTACT NOW</div>-->
<!--<div class="boxcontact2">
	<style>
		
		.boxcontactPhone{
			margin-left: 10px;
		}
		.closeboxphone{
			color: #fff;
		}
		.closeboxphone:hover{
			color: #fff;
		}
		.social-mxh-button{
			display: none;			
		}
	
		.social-mxh-text{
	transform: rotate(-90deg);
    color: #000;
    width: 150px;
    height: 40px;
    background: #FCD200;
    position: fixed;
    top: 300px;
    left: -55px;
    text-align: center;
    vertical-align: middle;
    display: inline-table;
    padding-top: 10px;
    cursor: pointer;
    border-radius: 0px 0px 10px 10px;
		}
		
	</style>
	
	<a href="https://api.whatsapp.com/send?phone=84989898198" class="boxc2 phonehv">
		<img src="/public/images/phone.png" class="item"></a>
    <a href="viber://chat?number=%2B84989898198" class="boxc2 viberhv"><img src="/public/images/viber.png" class="item"></a>
    <a href="http://zalo.me/84989898198" class="boxc2 zalohv"><img src="/public/images/zalo.png" class="item"></a>
    <a href="http://m.me/jackiehan.vn" class="boxc2 messagehv"><img src="/public/images/message.png" class="item"></a>
    <a href="tel:84989898198" class="boxc2 callbackhv"><img src="/public/images/callback.png" class="item"></a>
    <div class="boxcontactPhone"><a href="javascript:void(0)" onclick="closeBoxPhone()" class="closeboxphone"><i class="fa fa-close" title="Thu lại"></i></a>
    </div>
	</div>-->

<style>
/* Propeller typography */
/*@import "http://propeller.in/components/typography/css/typography.css";*/

/* Propeller buttons */
@import "http://propeller.in/components/button/css/button.css";

/* Propeller icons */
@import "http://fonts.googleapis.com/icon?family=Material+Icons";
@import "http://propeller.in/components/icons/css/google-icons.css";

/* Propeller css for Floating Action Button*/
.pmd-floating-action { bottom: 0; position: fixed;  margin:1em;  left: 0; }
.pmd-floating-action-btn { display:block; position: relative; transition: all .2s ease-out; }

.pmd-floating-action-btn:before { bottom: 10%; content: attr(data-title); opacity: 0; position: absolute; left: 100%; transition: all .2s ease-out .5s;  white-space: nowrap; background-color:#fff !important; padding:6px 12px; border-radius:2px; color:#333; font-size:12px; margin-left:5px; display:inline-block; box-shadow: 0px 2px 3px -2px rgba(0, 0, 0, 0.18), 0px 2px 2px -7px rgba(0, 0, 0, 0.15);}
.pmd-floating-action-btn:last-child:before { font-size: 14px; bottom: 25%;}
.pmd-floating-action-btn:active, .pmd-floating-action-btn:focus, .pmd-floating-action-btn:hover {box-shadow: 0px 5px 11px -2px rgba(0, 0, 0, 0.18), 0px 4px 12px -7px rgba(0, 0, 0, 0.15);}
.pmd-floating-action-btn:not(:last-child){ opacity: 0; -ms-transform: translateY(20px) scale(0.3); transform: translateY(20px) scale(0.3); margin-bottom:15px; margin-left:8px; position:absolute; bottom:0;}
.pmd-floating-action-btn:not(:last-child):nth-last-child(1) { transition-delay: 50ms;}
.pmd-floating-action-btn:not(:last-child):nth-last-child(2) { transition-delay: 100ms;}
.pmd-floating-action-btn:not(:last-child):nth-last-child(3) { transition-delay: 150ms;}
.pmd-floating-action-btn:not(:last-child):nth-last-child(4) { transition-delay: 200ms;}
.pmd-floating-action-btn:not(:last-child):nth-last-child(5) { transition-delay: 250ms;}
.pmd-floating-action-btn:not(:last-child):nth-last-child(6) { transition-delay: 300ms;}
.pmd-floating-action:hover .pmd-floating-action-btn, .menu--floating--open .pmd-floating-action-btn { opacity: 1; -ms-transform: none; transform: none; position:relative; bottom:auto;}
.pmd-floating-action:hover .pmd-floating-action-btn:before, .menu--floating--open .pmd-floating-action-btn:before { opacity: 1; background: transparent;}
.pmd-floating-hidden{ display:none;}
.pmd-floating-action-btn.btn:hover{ overflow:visible;}

.pmd-floating-action-btn .ink{ width:50px; height:50px;}
</style>
<!-- Floating Action Button like Google Material -->
<div class="menu pmd-floating-action"  role="navigation"> 
	<a target="_blank" href="http://m.me/jackiehan.vn" class="pmd-floating-action-btn btn btn-sm pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-default" data-title="Messenger"> 
		<span class="pmd-floating-hidden">Messenger</span>
		<img width="36" height="36" src="/public/images/message.png" class="item">
	</a> 
	<a target="_blank" href="https://api.whatsapp.com/send?phone=84989898198" class="pmd-floating-action-btn btn btn-sm pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-default" data-title="whatsapp"> 
		<span class="pmd-floating-hidden">whatsapp</span> 
		<img width="36" height="36" src="/public/images/phone.png" class="item">
	</a> 
	<a target="_blank" href="viber://chat?number=%2B84989898198" class="pmd-floating-action-btn btn btn-sm pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-default" data-title="Viber"> 
		<span class="pmd-floating-hidden">Viber</span> 
		<img width="36" height="36" src="/public/images/viber.png" class="item">
	</a> 
	<a target="_blank" href="http://zalo.me/84989898198" class="pmd-floating-action-btn btn btn-sm pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-default" data-title="Zalo"> 
		<span class="pmd-floating-hidden">Zalo</span> 
		<img width="36" height="36" src="/public/images/zalo.png" class="item">
	</a> 
	<a href="tel:84989898198" class="pmd-floating-action-btn btn btn-sm pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-default" data-title="Hotline"> 
		<span class="pmd-floating-hidden">Hotline</span> 
		<img width="36" height="36" src="/public/images/callback.png" class="item">
	</a> 
	<a class="pmd-floating-action-btn btn pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-primary" data-title="Contact" href="javascript:void(0);"> 
		<span class="pmd-floating-hidden">Primary</span>
		<i class="material-icons pmd-sm">add</i> 
	</a> 
</div>
</div>
<?php //} ?>
<div id="back-to-top" class="back-to-top" data-toggle="tooltip" data-placement="right" title="Trở lên đầu trang"><span class="glyphicon glyphicon-circle-arrow-up text-primary"></span></div>

<div class="col-md-12 col-sm-12 copyright">
	    	 <div class="col-md-10 col-md-offset-1" style ="height: 70px; overflow: hidden;">
			   	 <div class="col-md-5 cl">
				   	<?php $statTracker = new Model_StatTracker();
					      $visits = $statTracker->getVisits(); 
					      $visits = $visits[0]['ip'];	
					   	 ?>
				   	 Khách ghé thăm hôm nay: <?php echo $visits; ?> <br/>
				   	 Copyright 2015 Hòa Bình Group - All Right Reserved
				   	 <a href="//www.dmca.com/Protection/Status.aspx?ID=2f1cb399-de48-4e61-a93a-69cbad2d15d1" title="DMCA.com Protection Status" class="dmca-badge"> <img src ="https://images.dmca.com/Badges/dmca_protected_sml_120l.png?ID=2f1cb399-de48-4e61-a93a-69cbad2d15d1"  alt="DMCA.com Protection Status" /></a>  <script src="https://images.dmca.com/Badges/DMCABadgeHelper.min.js"> </script>
				   	 </div>	
				   	 
			   	 	
			   	 <div class="col-md-7">
				   	 <ul class="bottom_links pull-right">
							<li><img width="70" height="30" src="/public/images/PATA%20Member%20Logo%20H.JPG"></li>
							<li> <img width="70" height="30" src="http://hoabinh-group.com/public/images/japan-circle.jpg"></li>
							<li><img width="70" height="30" src="http://hoabinhtourist.com/images/hanoi_vnesco_travel.png"></li>
							<li><img width="70" height="30" src="http://hoabinhtourist.com/images/vcci.png"></li>
							<li style="background: #fff;height: 40px"><img width="70" height="30" src="http://hoabinhtourist.com/images/VISTA2015.png"></li>
							
						</ul>
			   	 </div>	
			   </div>
		   </div>
		   
		  
       <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
    <!-- Latest compiled and minified JavaScript -->
<script src="/public/js/vendor-hbg.min.js?v=1.1"></script>
<script src="/public/js/custom.function.min.js?v=1.1"></script>
   
    <?php echo $this->headScript() ?>
    <?php echo $this->InlineScript(); ?>
  
	<script>
	 $("#top_menu_louis").children('.topmenu-header').children('li:nth-child(4)').after('<li><div class="logo hidden-xs"><a class="navbar-brand" href="/"><img alt="Logo Hòa Bình Group" width="220" src="/public/images/logo-01.png" /></a></div></li>');			
	</script>
	
	

  </body>
</html>