<style>
	@media only screen and (max-width: 767px) {
		#louis-panel-contact{
			position: relative;
			top: -30px;
			left: 0%;
			margin-left: 0px;
		}
	}
</style>

 <div class="bg-header-page" style="background-image: url('<?=TEMPLATE_URL?>/default/img/banner-layout-visa-purchase-alerts-background.jpg'); background-position: 0px 0px;background-attachment: fixed;">
		   <div class="container"> <div class="row">

		 <h1 style="color: #272f67">Liên hệ với chúng tôi</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a style="color: #272f67" href="#">Trang chủ</a></li>
  <li class="breadcrumb-item active" style="color: #272f67 !important;">Liên hệ</li>
</ol>

 </div> </div>
	    </div>
	    
	    <div class="row" id = "news-content">
	    <div class="review-content">
		    <!-- <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyDhTdCH19UwecCmbWMNQrgMTh7tDQXavx0"></script>-->
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7448.362395461638!2d105.83199977592146!3d21.02543463821877!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab9c2bcea369%3A0x601713babedb164b!2zMjkgxJBvw6BuIFRo4buLIMSQaeG7g20sIFF14buRYyBU4butIEdpw6FtLCDEkOG7kW5nIMSQYSwgSMOgIE7hu5lpLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1589964552462!5m2!1svi!2s" width="100%" height="800" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
		   
  
	   <div class="col-md-7"></div>
	    	<div id="louis-panel-contact" class="col-md-5 col-xs-12">
	     <div class="panel">
    <div class="panel-heading">LIÊN HỆ VỚI CHÚNG TÔI</div>
    <div class="panel-body">
	    <div id="loadding">
	    	
	    </div>
	    <form name="contactForm" id="contactForm" method="post" action="/default/contact/submit">
	    <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="name" id="name" placeholder="Tên khách hàng" type="text" required autofocus />
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="email" id="email" placeholder="Địa chỉ Email" type="text" required />
                                </div>
                            </div>
                          
         <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="phone" id="phone" placeholder="Số điện thoại" type="text" required autofocus />
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="company" id="company" placeholder="Địa chỉ" type="text" />
                                </div>
                            </div>              
                           
            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12" style="padding-bottom: 10px;">
             <div class="form-group">
  <select name="request" class="form-control" id="request">
	  <option>Chọn loại yêu cầu</option>
    <option value="Yêu cầu khác">Khác</option>
    <option value="Khiếu nại dịch vụ">Khiếu nại dịch vụ</option>
    <option value="Yêu cầu tư vấn">Yêu cầu tư vấn</option>
    <option value="Yêu cầu hợp tác">Yêu cầu hợp tác</option>
  </select>
</div>
                                </div>
                            </div>
            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <textarea name="message" id="message" style="resize:vertical;" class="form-control" placeholder="Nội dung liên hệ..." rows="6" name="comment" required></textarea>
                                </div>
                            </div>
                            
             <div class="row">
	           <input type="submit" value="GỬI YÊU CẦU" class="submit-contact">
             </div>
	    </form>
            <div class="row" style="padding: 20px;">
	           <p>  <h5>LIÊN HỆ TRỰC TIẾP VỚI HÒA BÌNH GROUP</h5></p>
	            
	          <p><i class="fa fa-map-marker" aria-hidden="true"></i> <b> Trụ sở tại Hà Nội:</b> <br/>
	            Hotline: +84.913.311.911
	          </p>
	          <p>
	           <i class="fa fa-map-marker" aria-hidden="true"></i><b> Văn phòng miền Trung:</b> <br/>
	            Hotline: +84.913.186.829
	          </p>
	          <p>
	          <i class="fa fa-map-marker" aria-hidden="true"></i> <b>  Văn phòng miền Nam:</b> <br/>
	            Hotline: +84.98.98.98.198
	          </p>
            </div>
          
    </div>
    
   		 </div><!--.panel-->
	    	  
	    	
	    	</div>
	    </div>	
	      </div>
	      
	     
	      
	      
<script type="text/javascript">
	
	
/*	 var frmContact = $('#contactForm');
    frmContact.submit(function (ev) {
	    ev.preventDefault();	   
	    var  nameContact = $('#name').val();
	 var  emailContact = $('#email').val();
	 var  phone = $('#phone').val();
	    if ((nameContact == '') || (nameContact == null)){
		    alert('Please enter Your Name!');
		    return false;
	    }else if(emailContact == ''){
		    alert('Please enter Your Email!');
		     return false;
		 }}else if(phone == ''){
		    alert('Please enter Your Phone!');
		     return false;
		 }
    			
 
        $.ajax({
            type: frmContact.attr('method'),
            url: frmContact.attr('action'),
            data: frmContact.serialize(),
            success: function (data) {
               // console.log(data);
				   alert('Cám ơn quý khách!');
				  // $(this).fadeOut('fast');
		
                
              
            }
        });
*/
       
</script>
	