<!DOCTYPE html>
<html>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- no cache headers -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="Cache-Control" content="no-cache">
<!-- end no cache headers -->

   	 <title>Quản trị Admin</title>
   	 <?php echo $this->headTitle(); ?>
   	 <?php echo $this->headMeta(); ?>

		<link rel="stylesheet" href="/public/assets/css/bootstrap.css" />
		<link rel="stylesheet" href="/public/assets/css/font-awesome.css" />

		<!-- page specific plugin styles -->
		<link rel="stylesheet" href="/public/assets/css/jquery-ui.custom.css" />
		<link rel="stylesheet" href="/public/assets/css/chosen.css" />
		<link rel="stylesheet" href="/public/assets/css/datepicker.css" />
		<link rel="stylesheet" href="/public/assets/css/bootstrap-timepicker.css" />
		<link rel="stylesheet" href="/public/assets/css/daterangepicker.css" />
		<link rel="stylesheet" href="/public/assets/css/bootstrap-datetimepicker.css" />
		<link rel="stylesheet" href="/public/assets/css/colorpicker.css" />
		<link rel="stylesheet" href="/public/assets/css/custom_admin.css" />
		<link rel="stylesheet" href="/public/assets/css/prettify.css" />


		<!-- text fonts -->
		<link rel="stylesheet" href="/public/assets/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="/public/assets/css/ace.css" class="ace-main-stylesheet" id="main-ace-style" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="/public/assets/css/ace-part2.css" class="ace-main-stylesheet" />
		<![endif]-->

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="/public/assets/css/ace-ie.css" />
		<![endif]-->

		<!-- inline styles related to this page -->
	<?php echo $this->headLink(); ?>
   	 <?php echo $this->headScript(); ?>
		<!-- ace settings handler -->
		<script src="/public/assets/js/ace-extra.js"></script>


<!-- Event snippet for Lượt đăng ký Hòa Bình conversion page
In your html page, add the snippet and call gtag_report_conversion when someone clicks on the chosen link or button. -->
<script>
function gtag_report_conversion(url) {
  var callback = function () {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  };
  gtag('event', 'conversion', {
      'send_to': 'AW-804905149/BGu_CJTB2bUBEL3B5_8C',
      'event_callback': callback
  });
  return false;
}
</script>
	</head>

<body class="no-skin">

		<div id="navbar" class="navbar navbar-default">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">
				<!-- #section:basics/sidebar.mobile.toggle -->
				<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
					<span class="sr-only">Toggle sidebar</span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>
				</button>

				<!-- /section:basics/sidebar.mobile.toggle -->
				<div class="navbar-header pull-left">
					<!-- #section:basics/navbar.layout.brand -->
					<a href="#" class="navbar-brand">
						<small>
							<i class="fa fa-leaf"></i>
							Louis Admin
						</small>
					</a>

					<!-- /section:basics/navbar.layout.brand -->

					<!-- #section:basics/navbar.toggle -->

					<!-- /section:basics/navbar.toggle -->
				</div>

				<!-- #section:basics/navbar.dropdown -->
				<div class="navbar-buttons navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">
						<li class="grey">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="ace-icon fa fa-tasks"></i>
								<span class="badge badge-grey">0</span>
							</a>


						</li>

						<li class="purple">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="ace-icon fa fa-bell icon-animated-bell"></i>
								<span class="badge badge-important">0</span>
							</a>


						</li>

						<li class="green">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="ace-icon fa fa-envelope icon-animated-vertical"></i>
								<span class="badge badge-success">0</span>
							</a>

						</li>

						<!-- #section:basics/navbar.user_menu -->
						<li class="light-blue">
							<?php     try {
		 echo $this->layout()->userForm = $this->action('showinfouser', 'admin-user','user');

				    } catch (Zend_Exception $e) {
				        echo "Caught exception: " . get_class($e) . "\n";
				        echo "Message: " . $e->getMessage() . "\n";

				    }
				      ?>
						</li>

						<!-- /section:basics/navbar.user_menu -->
					</ul>
				</div>

				<!-- /section:basics/navbar.dropdown -->
			</div><!-- /.navbar-container -->
		</div>

		<div class="main-container" id="main-container" style="position: relative;min-height: 100%;">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

				<div id="sidebar" class="sidebar responsive">
					<?php echo $this->layout()->adminMenu = $this->action('render', 'menu', 'admin', array('menu' => 3)); ?>
				</div>

				<!-- /section:basics/sidebar -->
			  <div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">

							<?php echo $this->AdminBreadcrumbs(); ?>

						</ul><!-- .breadcrumb -->

						<!-- #section:basics/content.searchbox -->
						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- /.nav-search -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						 <?php echo $this->layout()->content; ?>
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->

			  <div class="footer">
				<div class="footer-inner">
					<!-- #section:basics/footer -->
					<div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Louis</span>
							Application &copy; 2016
						</span>

						&nbsp; &nbsp;
						<span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
					</div>

					<!-- /section:basics/footer -->
				</div>
			</div>

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->



			<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='/public/assets/js/jquery1x.js'>"+"<"+"/script>");
</script>
<![endif]-->

		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='/public/assets/js/jquery.mobile.custom.js'>"+"<"+"/script>");
		</script>

		<script src="/public/assets2/js/bootstrap.min.js"></script>
		<script src="/public/assets2/js/chosen.jquery.min.js"></script>
		<!-- page specific plugin scripts -->
		<script src="/public/assets2/js/jquery.dataTables.min.js"></script>
		<script src="/public/assets2/js/jquery.dataTables.bootstrap.min.js"></script>
		<script src="/public/assets2/js/dataTables.buttons.min.js"></script>
		<script src="/public/assets2/js/buttons.flash.min.js"></script>
		<script src="/public/assets2/js/buttons.html5.min.js"></script>
		<script src="/public/assets2/js/buttons.print.min.js"></script>
		<script src="/public/assets2/js/buttons.colVis.min.js"></script>
		<script src="/public/assets2/js/dataTables.select.min.js"></script>

		<!-- ace scripts -->
		<script src="/public/assets2/js/ace-elements.min.js"></script>
		<script src="/public/assets2/js/ace.min.js"></script>

		<script src="/public/js/functions.js" type="text/javascript"></script>

		<script type="text/javascript">
	/*if($('.date-picker').length){
	$('.date-picker').datepicker({
					autoclose: true,
					todayHighlight: true
				});
				}
				*/

	$(function () {
    setNavigation();
	});


		/*
		if($('a').attr('href') === '/admin/new/list') {
			$(this).parent().parent().parent().addClass('open');

   			}
   			*/
		</script>



	</body>

</html>
