<div class="container">
	<div class="row">
		<ul class="list-group">
			<?php foreach($this->row as $key => $row): ?>
			<li class="list-group-item">
			<div class="row">
				<div class="col-md-4">
					<?php echo $key; ?>
				</div>
				<div class="col-md-8">
					<?php echo $row; ?>
				</div>
			</div><!-- .row -->
			</li>
			<?php endforeach; ?>
		</ul>
	</div><!-- .row -->
</div><!-- .container -->