<?php
		//$this->headLink()->setStylesheet('https://cdn.datatables.net/tabletools/2.2.4/css/dataTables.tableTools.min.css');
	
	
		?>
	<div class="row">
		

									<div class="col-xs-12">
										<h3 class="header smaller lighter blue">Danh mục đăng ký thư pháp</h3>
									
<?php
if($this->registration != null) {
?>

<?php
	function getcaligraphy($id)
    {
	 
	    	$data = array(
		    	'Chưa chọn',
		    	'Chữ Hòa',
		    	'Chữ Trí',
		    	'Chữ Đạt',
		    	'Chữ Hạnh',
		    	'Chữ Phát',
		    	'Chữ Nhẫn',
		    	'Chữ Đức',
		    	'Chữ An'
	    	);	
	    	return $data[$id];	
	    	 
    }
    ?>
    <div class="clearfix">
					<div class="pull-right tableTools-container"></div>
				</div>
										<div class="table-responsive">
											<table id="table_events" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														<th class="center">
															<label>
																<input type="checkbox" class="ace" />
																<span class="lbl"></span>
															</label>
														</th>
														
														<th>Họ tên</th>
												
														<th>Điện thoại</th>
														<th>Email</th>
														<th>Ngày đăng ký</th>
														<th>Chữ yêu cầu</th>														
														<th>Vip</th>
														<th>Đã dùng dv</th>
														<th>Trạng thái</th>														
														<th class="center sorting_disabled">Xóa</th>
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('_registration-row.phtml', array_map(function($item){
						$item['calitext'] =  getcaligraphy($item['calitext']);
					return $item;
				}, $this->registration)); ?>																						

												</tbody>
											</table>
										</div>
	<?php }else{?>
<p>Chưa có người đăng ký!</p>
<?php }?>									
										
									</div>
								</div>
	<br/>
	

<script type="text/javascript">
 
 function toggleStatus(o, status)
 {
	 let id = $(o).attr('data-id');
	 
	 
	 
	 $.ajax({
	   type: 'POST',
	   url: '/admin/registration/status',
	   data: {
		   id: id,
		   status: status,
		   }
	   ,
	   success: function(data){
		 
		   
	     console.log('success',data);
	     
	      if(status == 1){
			$(o).html('<i class="fa fa-eye bigger-130"></i>');  
			console.log($(o));
			$(o).attr('onclick', 'toggleStatus(this, 0)');
		  } else{
			$(o).html('<i class="fa fa-eye-slash bigger-130"></i>');  
			$(o).attr('onclick', 'toggleStatus(this, 1)');
		  }
	   },
	   error: function(xhr, type, exception) { 
	     // if ajax fails display error alert
	     alert("ajax error response type "+type);
	   }
	 });
	 
 }
  
 </script>	
						
<script type="text/javascript">
	
	
			jQuery(function($) {
				//$.fn.dataTable.TableTools.defaults.aButtons = ["pdf", "copy","csv","xls", "print"];
				
				var myTable = $('#table_events').DataTable( {
				//"dom": 'T<"clear">lfrtip',
				//"dom": 'lBfrtip',
				"aoColumns": [
			      { "bSortable": false },
			      null, { "bSortable": false },null, { "bSortable": false }, { "bSortable": false }, { "bSortable": false }, { "bSortable": false }, { "bSortable": false },
				  { "bSortable": false }
				],
				select: {
						style: 'multi'
					}
				 } );
				
				
				$.fn.dataTable.Buttons.defaults.dom.container.className = 'dt-buttons btn-overlap btn-group btn-overlap';
				
				new $.fn.dataTable.Buttons( myTable, {
					buttons: [
					  {
						"extend": "colvis",
						"text": "<i class='fa fa-search bigger-110 blue'></i> <span class='hidden'>Show/hide columns</span>",
						"className": "btn btn-white btn-primary btn-bold",
						columns: ':not(:first):not(:last)'
					  },
					  {
						"extend": "copy",
						"text": "<i class='fa fa-copy bigger-110 pink'></i> <span class='hidden'>Copy to clipboard</span>",
						"className": "btn btn-white btn-primary btn-bold"
					  },
					  {
						"extend": "csv",
						"text": "<i class='fa fa-database bigger-110 orange'></i> <span class='hidden'>Export to CSV</span>",
						"className": "btn btn-white btn-primary btn-bold"
					  },
					  {
						"extend": "excel",
						"text": "<i class='fa fa-file-excel-o bigger-110 green'></i> <span class='hidden'>Export to Excel</span>",
						"className": "btn btn-white btn-primary btn-bold"
					  },
					  {
						"extend": "pdf",
						"text": "<i class='fa fa-file-pdf-o bigger-110 red'></i> <span class='hidden'>Export to PDF</span>",
						"className": "btn btn-white btn-primary btn-bold"
					  },
					  {
						"extend": "print",
						"text": "<i class='fa fa-print bigger-110 grey'></i> <span class='hidden'>Print</span>",
						"className": "btn btn-white btn-primary btn-bold",
						autoPrint: false,
						message: 'This print was produced using the Print button for DataTables'
					  }		  
					]
				} );
				myTable.buttons().container().appendTo( $('.tableTools-container') );
				
				//style the message box
				var defaultCopyAction = myTable.button(1).action();
				myTable.button(1).action(function (e, dt, button, config) {
					defaultCopyAction(e, dt, button, config);
					$('.dt-button-info').addClass('gritter-item-wrapper gritter-info gritter-center white');
				});
				
				
				var defaultColvisAction = myTable.button(0).action();
				myTable.button(0).action(function (e, dt, button, config) {
					
					defaultColvisAction(e, dt, button, config);
					
					
					if($('.dt-button-collection > .dropdown-menu').length == 0) {
						$('.dt-button-collection')
						.wrapInner('<ul class="dropdown-menu dropdown-light dropdown-caret dropdown-caret" />')
						.find('a').attr('href', '#').wrap("<li />")
					}
					$('.dt-button-collection').appendTo('.tableTools-container .dt-buttons')
				});
			
				////
			
				setTimeout(function() {
					$($('.tableTools-container')).find('a.dt-button').each(function() {
						var div = $(this).find(' > div').first();
						if(div.length == 1) div.tooltip({container: 'body', title: div.parent().text()});
						else $(this).tooltip({container: 'body', title: $(this).text()});
					});
				}, 500);
				
				
				
				
				
				myTable.on( 'select', function ( e, dt, type, index ) {
					if ( type === 'row' ) {
						$( myTable.row( index ).node() ).find('input:checkbox').prop('checked', true);
					}
				} );
				myTable.on( 'deselect', function ( e, dt, type, index ) {
					if ( type === 'row' ) {
						$( myTable.row( index ).node() ).find('input:checkbox').prop('checked', false);
					}
				} );
			
			
				
				$('table th input:checkbox').on('click' , function(){
					var that = this;
					$(this).closest('table').find('tr > td:first-child input:checkbox')
					.each(function(){
						this.checked = that.checked;
						$(this).closest('tr').toggleClass('selected');
					});
						
				});
			
			
			});
		</script>									
