<!DOCTYPE html>
<html lang="vi" dir="ltr">
<head>
<title>Thư pháp tri ân khách hàng</title>
</head>
<body>
	<h3>Thông tin khách hàng đăng ký nhận thư pháp</h3>

<p>Tên khách hàng: <?=$this->name?></p> 
<p>Email: <?=$this->email?></p> 
<p>Điện thoại: <?=$this->mobile?></p> 
<!--<p>Nghề nghiệp: <?=$this->job?></p>-->
<p>Nơi công tác: <?=$this->company?></p> 
<p>Địa chỉ nhận tranh thư pháp: <?=$this->address?></p> 
<p>Tình trạng đăng ký dịch vụ Hoà Bình: <?php echo $this->used_service; ?></p>
<p>Dịch vụ mà bạn đã đăng ký: <?=$this->service?></p> 
<p>Giá trị dịch vụ: <?=$this->price?></p> 
<p>Nhân viên Hoà Bình Group bạn đã làm việc: <?=$this->staff?></p> 
<p>Chữ thư pháp bạn yêu cầu: <?=$this->calitext?></p> 

Liên hệ từ: http://hoabinh-group.com/page/thu-phap-tri-an-khach-hang

</body>
</html>