<!DOCTYPE html>
<html lang="vi" dir="ltr">
<head>
<title></title>
</head>
<body>
	<h3>Thông tin khách hàng đăng ký hội nghị Taiwan</h3>

<p>Tên khách hàng: <?=$this->name?></p> 
<p>Chức vụ: <?=$this->job?></p> 
<p>Email: <?=$this->email?></p> 
<p>Điện thoại: <?=$this->mobile?></p> 
<p>Công ty: <?=$this->company?></p> 
<p>Số người tham dự: <?=$this->number?> người</p> 

Đăng ký từ: http://hoabinh-group.com/page/dailoan/

</body>
</html>